version: '3'

services:
  app_v2:
    build: .
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
    volumes:
      - ./saudesimples:/saudesimples
      - bundle_path:/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/bundle/vendor
      - SIDEKIQ_REDIS_URL=redis://redis_v2:6379/1
      - TZ=America/Araguaina
    depends_on:
      - db_v2
    networks:
      - saude_simples
    external_links:
      - app_v3:app_v3

  db_v2:
    image: postgres:9.6.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - $HOME/.postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - saude_simples

  redis_v2:
    image: 'redis:7.0-rc2-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    networks:
      - saude_simples

  elasticsearch_v2:
    image: elasticsearch:5.6.16
    ports:
    - '9200:9200'
    depends_on:
      - db_v2
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - saude_simples

  jasperserver_v2:
    image: ghcr.io/om30/jasperserver:7.1.0
    # restart: always
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - db_v2
    environment:
      WEB_APP_NAME_CE: jasperserver
      DB_TYPE: postgresql
      DB_PORT: 5432
      DB_HOST: db_v2
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - saude_simples

volumes:
  db_data:
  redis:
  bundle_path:
  elasticsearch-data:

networks:
  saude_simples:
    external: true